SELECT
  CAST(ORDER_ID AS INT) AS ORDER_ID,
  CAST(ORDER_ITEM_ID AS INT) AS ORDER_ITEM_ID,
  CAST(PRODUCT_ID AS INT) AS PRODUCT_ID,
  CAST(QUANTITY AS NUMERIC) AS QUANTITY
FROM {{ source('grocery_store', 'order_items') }}
WHERE TRY_CAST(QUANTITY AS NUMERIC) IS NOT NULL

