sample_dbt:
  outputs:
    dev:
      type: snowflake
      account: OVMHUPB-NA98462
      warehouse: WH_DBT_JHO
      database: DBT_JHO
      role: ROLE_DBT_JHO
      schema: ANALYTICS
      user: USER_JHO
      authenticator: externalbrowser
      threads: 4
    ci: # see https://docs.getdbt.com/docs/core/connect-data-platform/snowflake-setup#key-pair-authentication
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA') }}"
      user: "{{ env_var('SNOWFLAKE_CI_USER') }}"
      private_key: "{{ env_var('SNOWFLAKE_CI_USER_PRIVATE_KEY') }}"
      private_key_passphrase: "{{ env_var('SNOWFLAKE_CI_USER_PRIVATE_KEY_PASSPHRASE') }}"
      threads: 4
    prod: # see https://docs.getdbt.com/docs/core/connect-data-platform/snowflake-setup#key-pair-authentication
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') }}"
      schema: "{{ env_var('SNOWFLAKE_SCHEMA') }}"
      user: "{{ env_var('SNOWFLAKE_CD_USER') }}"
      private_key: "{{ env_var('SNOWFLAKE_CD_USER_PRIVATE_KEY') }}"
      private_key_passphrase: "{{ env_var('SNOWFLAKE_CD_USER_PRIVATE_KEY_PASSPHRASE') }}"
      threads: 4
  target: dev
