name: dbt CD

on:
  release:
    types: [published]

jobs:
  dbt-deploy:
    runs-on: ubuntu-latest

    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
      SNOWFLAKE_CD_USER: ${{ secrets.SNOWFLAKE_CD_USER }}
      SNOWFLAKE_CD_USER_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_CD_USER_PRIVATE_KEY }}
      SNOWFLAKE_CD_USER_PRIVATE_KEY_PASSPHRASE: ${{ secrets.SNOWFLAKE_CD_USER_PRIVATE_KEY_PASSPHRASE }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dbt and dependencies
        run: pip install -r requirements.txt

      - name: Install dbt packages
        run: dbt deps --profiles-dir ./profiles
        working-directory: ./dbt_101

      - name: Deploy dbt models
        run: dbt build --target prod --profiles-dir ./profiles
        working-directory: ./dbt_101
