name: dbt CI

on:
  pull_request:
    branches: [ main ]

jobs:
  dbt-ci:
    runs-on: ubuntu-latest

    env:
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
      SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_PASSPHRASE }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dbt and dependencies
        run: pip install -r requirements.txt

      - name: Install dbt packages
        run: dbt deps --profiles-dir ./profiles
        working-directory: ./dbt_101

      - name: Debug dbt profile connection
        run: dbt debug --target dev --profiles-dir ./profiles
        working-directory: ./dbt_101

      - name: Run dbt models
        run: dbt run --target dev --profiles-dir ./profiles
        working-directory: ./dbt_101

      - name: Test dbt models
        run: dbt test --target dev --profiles-dir ./profiles
        working-directory: ./dbt_101
